### PR TITLE
Adding deploy commands

### PR DESCRIPTION
**Pull request by benfhicks**

### CODE REVIEW

**Comment by bgaytherUW** [comment]
Do we want to account for already running endpoints / deployed models?

In my [script](https://github.com/utilitywarehouse/nlp-email-verification/blob/main/cloudbuild.yaml), I un-deploy and recreate the endpoint from scratch so as not to duplicate endpoints/deployments.

**Comment by bgaytherUW** [comment]
Would the idea be to call the functions from this script in a cloudbuild.yaml, i.e.:

```
    - name: 'python'
      entrypoint: 'python'
      args: ['...']

```
If so, I think we will need some CLI arguments so the user can do this in their script:

```
    - name: 'python'
      entrypoint: 'python'
      args: ['mlops_tooling/serving/deployment.py', '--project=${PROJECT_ID}', '--model_name=${MODEL_NAME}`]

```

**Comment by benfhicks** [comment]
> Would the idea be to call the functions from this script in a cloudbuild.yaml? i.e.:
> 
> ```
>     - name: 'python'
>       entrypoint: 'python'
>       args: ['...']
> ```
> 
> If so, I think we will need some CLI arguments so the user can do this in their script:
> 
> ```
>     - name: 'python'
>       entrypoint: 'python'
>       args: ['mlops_tooling/serving/deployment.py', '--deploy-model', '--project=${PROJECT_ID}', '--model_name=${MODEL_NAME}`]
> ```

My thoughts were to just create a python file and use that to deploy:

```Python
from mlops_tooling.serving.deployment import deploy_model
import os

PROJECT = os.environ.get("MODEL_PROJECT", "project")
...

if __name__ == 'main':
  deploy_model(PROJECT, ...)
```

We could do it as a CLI command, but we'd need to know where the `mlops_tooling/serving/deployment.py` file is whenever we want to run it

**Comment by benfhicks** [comment]
> Would the idea be to call the functions from this script in a cloudbuild.yaml? i.e.:
> 
> ```
>     - name: 'python'
>       entrypoint: 'python'
>       args: ['...']
> ```
> 
> If so, I think we will need some CLI arguments so the user can do this in their script:
> 
> ```
>     - name: 'python'
>       entrypoint: 'python'
>       args: ['mlops_tooling/serving/deployment.py', '--deploy-model', '--project=${PROJECT_ID}', '--model_name=${MODEL_NAME}`]
> ```

Have added! Should be good to go I think :)

**Comment by bgaytherUW** [comment]
> > Would the idea be to call the functions from this script in a cloudbuild.yaml? i.e.:
> > ```
> >     - name: 'python'
> >       entrypoint: 'python'
> >       args: ['...']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If so, I think we will need some CLI arguments so the user can do this in their script:
> > ```
> >     - name: 'python'
> >       entrypoint: 'python'
> >       args: ['mlops_tooling/serving/deployment.py', '--deploy-model', '--project=${PROJECT_ID}', '--model_name=${MODEL_NAME}`]
> > ```
> 
> Have added! Should be good to go I think :)

Nice, no approval required, so merge when you'd like :)

**Pull request merged**
